Clarify README.md
kamon-io/kamon-logback pull request #16
Opened 2019-01-08 16:46 UTC by chotai

Update `kamon-logback` version in README.md to reflect that the feature to add custom values to MDC was only added in v1.0.3

Add logback.xml example to AsyncAppender to clarify how `AsyncAppenderInstrumentation` is configured.

2019-01-09 22:24 UTC, ivantopo requested changes

2019-01-09 22:24 UTC, ivantopo commented on README.md
> +  <!--Use this appender to see the MDC context propagated by kamon.logback.instrumentation.AsyncAppenderInstrumentation-->
This is not really really true.. even though the instrumentation file mentions the AsyncAppender, everything that has to do with MDC is not tied to it. It will work the same if you the ConsoleAppender directly.

You can either mention that Kamon will keep the context across the async boundary on the AsyncAppender or remove this line :slightly_smiling_face:

2019-01-09 22:24 UTC, ivantopo commented on README.md
> +      <pattern>%d{yyyy-MM-dd HH:mm:ss} | %-5level | %traceID | %c{0} -> %m%n</pattern>
It would be nice to mention some of the MDC keys from bellow, maybe userID?

```suggestion
      <pattern>%d{yyyy-MM-dd HH:mm:ss} | %-5level | %traceID %X{userID} | %c{0} -> %m%n</pattern>
```

2019-01-09 22:59 UTC, ivantopo commented on README.md
> +|  1.0.4 | stable | 1.8+ | 2.10, 2.11, 2.12
And, we just published 1.0.5, please update to that number :slightly_smiling_face:

2019-01-15 11:42 UTC, chotai commented on README.md
> +  <!--Use this appender to see the MDC context propagated by kamon.logback.instrumentation.AsyncAppenderInstrumentation-->
I'll remove this line 👍

2019-01-15 11:46 UTC, chotai commented on README.md
> +      <pattern>%d{yyyy-MM-dd HH:mm:ss} | %-5level | %traceID | %c{0} -> %m%n</pattern>
Good point

2019-01-15 12:28 UTC, chotai commented
Addressed your comments @ivantopo. Let me know if you're happy with these changes 👍

2019-05-13 15:30 UTC, closed without merging