A appender that counts log entries
kamon-io/kamon-logback pull request #19
Opened 2019-02-27 14:02 UTC by opbokel

Hello, I would like to give you a little bit of context

My name is Octavio and I work at Fedex. We got the need for counting every log entry as a Kamon metric, that way we can easily visualize, and most important, make alerts based on the log counts.

I created this appender that will count each log entry, split by level, so it can be extract as a regular metric. The main advantage is that no code change is needed, just the logback XML configuration.

Would you please consider merging this PR?

Thanks for your consideration.

2019-03-06 14:01 UTC, ivantopo requested changes
Hey @opbokel, thanks for proposing this! There are a few things to discuss but in general this seems a really useful addition to this module :tada:

There is one more thing on my mind: should we somehow apply this appender automatically via bytecode instrumentation? :thinking:... we already had some ideas for that in mind long time ago so maybe we can turn all of this into a single solution that covers both cases.

/cc @dpsoft @mladens

2019-03-06 14:01 UTC, ivantopo commented on src/main/resources/reference.conf
> +    entries-counter {
I'm a bit curious about the need to configure this metric/tag names. If we follow the (implicit) conventions around Kamon this metric should probably be called something like `log.events` and have a `level` tag, plus a `component=logback` tag.. then if we ever get to do the same for log4j or any other provider we can have the same metric from a different component.

That being said, do you see cases (at least within your organization) where the name should be customized somehow?

2019-03-06 14:01 UTC, ivantopo commented on src/main/scala/kamon/logback/LogbackEntriesCounterAppender.scala
> +  private val appenderConfig = Kamon.config().getConfig("kamon.logback.entries-counter")
I'm not sure if this will remain configurable based on the comment I left above, but if we end up doing that this should be "reconfigurable"

2019-03-06 14:01 UTC, ivantopo commented on src/test/scala/kamon/logback/KamonMemoryMetricReporter.scala
> +class KamonMemoryMetricReporter extends MetricReporter {
This is not a completely necessary change, but instead of creating a reporter and so on you could use this: https://github.com/kamon-io/Kamon/blob/master/kamon-testkit/src/main/scala/kamon/testkit/MetricInspection.scala

2019-03-06 14:20 UTC, opbokel commented on src/main/resources/reference.conf
> +    entries-counter {
I agree. It was supposed to be a plus, but don't add much! I will change.

2019-03-06 14:20 UTC, opbokel commented on src/main/scala/kamon/logback/LogbackEntriesCounterAppender.scala
> +  private val appenderConfig = Kamon.config().getConfig("kamon.logback.entries-counter")
I removed, thanks

2019-03-06 14:22 UTC, opbokel commented on src/test/scala/kamon/logback/KamonMemoryMetricReporter.scala
> +class KamonMemoryMetricReporter extends MetricReporter {
I see, but do you mind leaving like this for the first version?

2019-03-07 08:45 UTC, opbokel commented on src/test/scala/kamon/logback/KamonMemoryMetricReporter.scala
> +class KamonMemoryMetricReporter extends MetricReporter {
I am resolving since you said is not completely necessary. I will consider this change for a second version.

2019-03-07 08:54 UTC, opbokel commented
Hello, I truly believe in incremental improvements.

There are ways to improve this solution, but right now, it is the simplest solution possible to achieve the desired effect.

The user only needs to add one line to the logback XML and that is it, and the code is simple.

2019-03-15 10:48 UTC, ivantopo commented
Hey @opbokel this PR looks pretty nice now, the only thing I'm going to ask you before merging it is to add a small section to the readme explaining what this brings and how to use it. A minimal `logback.xml` with this appender would be awesome so users can just copy-paste it and that's it.

Thanks!

2019-03-20 09:46 UTC, opbokel commented
Updated the README.md, please take a look.

2019-03-26 09:31 UTC, merged